// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using productApi.Data;

#nullable disable

namespace ProductApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240214205227_addfastningbook")]
    partial class addfastningbook
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProductApi.Models.FastningBook", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Efternavn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FaestebrevUdstedt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FaesterNavn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FaesterTilNavn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Film")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fornavn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ForrigeFaesterEfterNavn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ForrigeFaesterForNavn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ForrigeFaesterNavn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ForrigeFaesterTilNavnmm")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gaard")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Herred")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Indskrivningsnr")
                        .HasColumnType("int");

                    b.Property<string>("Kommentarer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Side")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sogn")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("FastningBooks");
                });
#pragma warning restore 612, 618
        }
    }
}
